Changed libx264-5.json, further test needed
Vouk/voukoder pull request #126
Opened 2022-04-19 02:01 UTC by iAvoe

I've used VSCode and edited those 2 files, and made sure the json format was correct and all parameters are linked to the definitions in the bottom part of file.
However due to I've mainly worked with x265.exe instead of libx265, some parameters are missing in libx265 and I cannot gurantee they actually will work (some parameter may get deleted or the definitions needs to be modified if libx265 v3.5 persists not recognizing)
Software is not my profession and I wish I could compile and test the changes myself. Someone needs to compile and check in software to see if the parameters are applied correctly.
Changes also happened in x264 parameters, they have been separated with color profiles (4:2:0 and 4:4:4) thus creates more versions, just 1 version needs to be tested for them.

2022-04-19 02:09 UTC, iAvoe commented
For libx264, the "fgo" option was not included, maybe a different branch have that;
For libx265, the "allow-non-conformance" option was not included, this one is pretty important and needs a libx265 that supports this option;
For libx265, the "selective-sao" option was not included, this one is not very important and can be ignored;
For libx265, the "defalts {}" section may not work with lossless options, needs forther test. If that's true, move those options back to the existing parameter sections.
I've also edited the description of each parameter section to note these potential issues. Hopefully this works :)

2022-04-20 09:47 UTC, Vouk requested changes

2022-04-20 09:47 UTC, Vouk commented on Core/resources/encoders/libx264.json
> +        "preset": "meduim",
typo - should be "medium"

2022-04-20 09:47 UTC, Vouk commented on Core/resources/encoders/libx264.json
> +     "description": "by iAvoe. There are no option listed for bit-depth, and the implementation of _pixelFormat does not relate to bit depth; may needs a test on 10bit projects",
bit depth is decided by selecting the pixel format:
yuv420p: 8 bit
yuv420p10le: 10 bit

2022-04-20 09:47 UTC, Vouk commented on Core/resources/encoders/libx264.json
> +     "name": "4:4:4 General purpose, 8-10bit projects (ProRes alternative)",
Pix format is yuv444p10le, so only 10 bit, you'd need to add a second preset with 8 bit. Or we just present 8 bit presets and people need to switch manually to 10 bit?

2022-04-20 09:47 UTC, Vouk commented on Core/resources/encoders/libx265.json
> +   "description": "1.Some libx265-s are missing the option: allow-non-conformance, make sure this parameter exists, otherwise encoder may refuse to start. 2.Default parameters may collide with lossle
"defaults" apply to all configurations, not only presets, but even manual ones. So i don't think setting it like this is a good decision.

You can add "allow-non-conformance" if you want, just add this option .. maybe under "misc".

2022-04-21 03:22 UTC, iAvoe commented on Core/resources/encoders/libx264.json
> +     "name": "4:4:4 General purpose, 8-10bit projects (ProRes alternative)",
From what I saw, yuv444p10le supports both 8 and 10 bit. But just in case I could be wrong, I've splitted that into 2 presets: yuv444p and yuv444p10le. Switching maually may not be user friendly in my experience, that was the reason I splitted them :)

2022-04-21 03:23 UTC, iAvoe commented on Core/resources/encoders/libx264.json
> +     "description": "by iAvoe. There are no option listed for bit-depth, and the implementation of _pixelFormat does not relate to bit depth; may needs a test on 10bit projects",
I'll change the name from 8-10 bit to 10bit

2022-04-21 03:28 UTC, iAvoe commented on Core/resources/encoders/libx265.json
> +   "description": "1.Some libx265-s are missing the option: allow-non-conformance, make sure this parameter exists, otherwise encoder may refuse to start. 2.Default parameters may collide with lossle
I've moved options away from default. I've read through [the source code](https://bitbucket.org/multicoreware/x265_git), but was not able to find the proper way of adding allow-non-conformance, as a little bit of python is add my knowledge to coding (sorry)

2022-04-21 03:37 UTC, iAvoe commented on Core/resources/encoders/libx264.json
> +     "name": "4:4:4 General purpose, 8-10bit projects (ProRes alternative)",
Since the preset tab in the program is not fully populated, I'd say present both is better, if the space gets crammed then remove some 10bit presets would be better.

2022-04-21 03:39 UTC, iAvoe commented
1 issue left to be worked: I was not able to find the way of adding "allow-non-conformance". Currently it's in the presets section, but I didn't find how to fill the "id" value.

2022-04-25 15:31 UTC, Vouk commented on Core/resources/encoders/libx265.json
> +      "allow-non-conformance",
I have added the parameter down below.

2022-04-25 21:41 UTC, iAvoe commented
**Removed in v3.5:**
`scenecut-window, max-qp-delta, qp-delta-ref & qp-delta-nonref (replaced by scenecut-aware-qp)`
**Added in v3.5:**
`scenecut-aware-qp (2pass), masking-strength (2pass), hdr10-opt (replacing hdr-opt), film-grain (specify film grain model file to import), min-vbv-fullness, max-vbv-fullness, vbv-live-multi-pass`

For version 3.5, the change happens mostly in performance improvements and "side feature options", but looking back to earlier versions (I can't remember exactly) there was some "main feature option" gets renamed (the best part is they didn't list change in release notes), it took me a while to figure out the cause lol

2022-04-25 22:07 UTC, iAvoe commented on Core/resources/encoders/libx265.json
> +      "description": "by iAvoe, require x265 v3.5 since some parameter names are changed; or new parameters added/deleted",
**General Purpose -->** 
```
4:2:0 General Purpose 8bit;
4:2:0 General Purpose 10bit;
4:4:4 General Purpose 8bit;
4:4:4 General Purpose 10bit
```
4:2:2 options are ignored to clearify use-cases

**General Purpose (Fast) -->**
```
4:2:0 General Purpose 8bit (Fast)
```
Clearifying use-case of this preset as "Quick Export"

**Lossless -->**
```
4:2:0 Lossless 8bit;
4:2:0 Lossless 10bit;
4:4:4 Lossless 10bit
```
4:4:4 Lossless 8bit was not added to clearify use-cases, but including it back is decent as well

**Good quality, high compression -->**
```
4:2:0 High compression 8bit;
4:4:4 High compression 8bit;
4:4:4 High compression 10bit;
```
4:4:4 Lossless 8bit was not added to clearify use-cases
Title "good quality" gets removed because all these presets are configured to be "good quality" :/

**High quality, high compression** (removed)
Removed as it didn't work as expected, and user really should go for hevc for higher compression

**Maximum Useful Cost Possible -->** 
```
4:4:4 Encode speed benchmark & stability stress test (parameter value changed)
```
This preset didn't really maxing out the cost in order to perserve quality, 4:4:4 high compression is also good enough to defeat the purpose of this preset. Therefore I've changed the use case to purely act as a stress test.

2022-04-26 06:53 UTC, Vouk approved these changes

2022-04-26 07:15 UTC, merged